spring:
  application:
    name: department-service
  config:
    import: "optional:configserver:http://localhost:8888"
# spring:
#   datasource:
#     url: jdbc:mysql://localhost:3306/staff_manager_db
#     username: root
#     password: root
#     driver-class-name: com.mysql.cj.jdbc.Driver
#   jpa:
#     open-in-view: false
#     hibernate:
#       ddl-auto: none
#     show-sql: true
#     database-platform: org.hibernate.dialect.MySQLDialect
#     properties:
#       hibernate:
#         format_sql: true
#   web:
#     resources:
#       add-mappings: false
#   output:
#     ansi:
#       enabled: ALWAYS
#   sql:
#     init:
#       mode: never
#   application:
#     name: department-service
#   cloud:
#     consul:
#       host: localhost
#       port: 8500
#       discovery:
#         # register: true
#         # enabled: true
#         health-check-path: /actuator/health
#         health-check-url: http://host.docker.internal:8082/actuator/health
#         ip-address: localhost
#         health-check-interval: 10s
#         service-name: ${spring.application.name}
#         prefer-ip-address: true
#   title: department micro service
#   version: 1.0
#   url:
#     front-end: http://localhost:4200
#   upload:
#     day-off-document:
#       max-size: 2_097_152  #2MB

# server:
#   port: 8082
#   error:
#     path: /error
# #  error:
# #    whitelabel:
# #      enabled: false

# logging:
#   level:
#     org:
#       # springframework:
#       #   orm: 
#       #     jpa: DEBUG
#       # hibernate: DEBUG
#         # orm:
#         #   jdbc:
#         #     bind: TRACE
#         # SQL: DEBUG
#     root: INFO

# management:
#   endpoint:
#     startup:
#       access: unrestricted
#     health:
#       show-details: always
#   endpoints:
#     web:
#       exposure:
#         include: '*'

# security:
#   jwt:
#     secret: Ns6SpnvuJgwRCli/WbFpCIPhBkhjBTYxE4VORK/dxRQ=
#     access-token-lifetime-milliseconds: 300_000
    
